### ISSUE TITLE
Can't get require-jsdoc-on-export rule to work

### ISSUE THREAD

**Issue by mnezh** [benderTheCrime/eslint-plugin-benderthecrime#5]
I'm trying to use the `benderthecrime/require-jsdoc-on-export` rule to work, by adding it to the .eslintrc file as:
```
"rules": {
    "benderthecrime/require-jsdoc-on-export": [
      2,
      {
        "ClassDeclaration": false,
        "FunctionDeclaration": true,
        "MethodDefinition": false
      }
    ]
  }
```
However, eslint is not happy with the configuration: 
```
Error: /Users/andrey.mishustin/Gits/iflix/foreplay/.eslintrc:
	Configuration for rule "benderthecrime/require-jsdoc-on-export" is invalid:
	Value "[object Object]" should be number.

    at validateRuleOptions (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config/config-validator.js:113:15)
    at Object.keys.forEach.id (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config/config-validator.js:153:9)
    at Array.forEach (native)
    at validateRules (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config/config-validator.js:152:30)
    at Object.validate (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config/config-validator.js:230:5)
    at loadFromDisk (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config/config-file.js:549:19)
    at Object.load (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config/config-file.js:592:20)
    at Config.getLocalConfigHierarchy (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config.js:228:44)
    at Config.getConfigHierarchy (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config.js:182:43)
    at Config.getConfigVector (/Users/andrey.mishustin/Gits/iflix/foreplay/node_modules/eslint/lib/config.js:287:21)
error Command failed with exit code 1.
```
I guess the reason might be the rule schema, which doesn't make sense to me at the first glance: https://github.com/benderTheCrime/eslint-plugin-benderthecrime/blob/9525036950f1e00ce6a0446e09eddb544131d668/lib/rules/require-jsdoc-on-export.js#L86

I was trying to get rid of the standard-jsdoc eslint behaviour requiring comments for virtually everything to more reasonable documenting the exports only.

**Comment by benderTheCrime** [comment]
This in interesting, thanks for raising an issue. 

On a personal note, I've mostly stopped using JSDoc in favor of an approach that has no comments as of a year and a half ago (hence the benderthecrime/no-comment rule). This rule should have been marked deprecated then, but it wasn't broken at the time.

I'm going to tell you right now that I have no idea what the original intent for the schema taking a number as it's first argument is or what configuring the types to false by default achieved. 

I think perhaps I'm going to show this rule some love by enabling all types by default and restructuring the rule to visit export AST types, checking against an "excludes" type list as a configuration parameter.

example:

```json
{
    "benderthecrime/require-jsdoc-on-export": [
      2,
      {
           "excludes": [
                "VariableDeclaration"
            ]
      }
    ]
}
```

any thoughts on this?

**Comment by mnezh** [comment]
Yes, I think it makes sense, since the rule already introduces reasonable limit on jsdoc requirements, enabling it for all exported entities by default is a good choice. If someone for any reason needs to limit it even more, `excludes` seems to be semantically adequate.

**Comment by benderTheCrime** [comment]
Ok, I'll follow up when I get on solid ground and can make a PR.

**Comment by benderTheCrime** [comment]
@mnezh https://github.com/benderTheCrime/eslint-plugin-benderthecrime/pull/6.
